language: node_js
node_js:
- '0.11'
- '0.10'
notifications:
  email: false
  slack:
    secure: FsplVnNoBHgZmZ4uitu5bRzjjjySAYg9w4gZ6Ch+ZgmY7dXxQ99ebVHqK7DaWbbp2rm3+wThtLz67Ia3SPgk2PeXORriHykJBn1gqPtj67aLGSC0KkFaastpVbCgxh9dKSFcyIzT/OiYcKmqQ+vgEKpqjpgljA8AgGxlToNA+h9i32sWR/l1PalAPk+uyqMW/fZoilWQ44fy0nyNxmIkbCQZF9cnuJUaRiAnDnazfF9+tw91QHYEkVkBCjF/oi9mcRaaQwqtE/Y13MQbivsDlp5UNnvMNFMCtGTL9BOfDqHqiEB+R3OTrN6644OU43ZuqSqs5cXOsuU1nC0/U3GiSJTosHAIfIrqSyPEmH9vO7DQH615ku2boMFqb7e/c0/5N9gRdWSeigj151nhe35gsTcTl5fCel/9xrWwYVx1apZhy7oVxS5MZS1hQG2UZBdkxf+G/VS/OtigDv/BzrB6j71t6kv0763NRd1ZrMXhYAS0aNkRRs9OxCH5O1VBn9ML/qmgxqSrenthnWqmfm2+KBVjCwvT5SEnf802ftTemleRi0nvdL0mq432YhTvaMVt0GHePQPRJ6JzVrVHeXLaVVRijza21kKESWE/z0NgbdXnAzrao0AlmDHDRuNEsLk3kWS1iwj088NYmazR/TmEGZAkJb7OulMYGj3sdG/k1Yk=
deploy:
  provider: heroku
  api_key:
    secure: qeF4QOouXdMJq3fxeEShI9lXW0PKWvv7gB+1AxK1tDGG12GbxUcWxKtRhLy19Q2yWDknODu+MYxU2c8H6ZQeG1uny5SHNxNRmCM6Mjuiohi4nR+xaTmPWrGmo7HxjwvMB4PMQk98nIO6Rnn8FpL/tjcBjwr9HTwyO3Io6jYPbounBtvOOgOXC4GZ5AWzamPEec/dK2LIFw39UayDsLh7dzM6p+Ddj9P5eynMliPN9JeGJjNyBpm3FVyZxUDsvgH8+u97a+dITea/qyDRW/RuCMVL4nWV6wNgAg1X9lfhwNZ5ORlr4QOXnWvYHabaLBF2ECz6pNmBqNAogMVuznbd2E9MmAWlFAh3x1g16KXwy6gSGn5/tDpez4/+PJQY1zE4RRswnGKLjJqVLoK/aZTzLswQJ1QEI5OOB18KsD1GxlR1fUZE4bia4D4/FaQEhkzIyvgGLp2cBzJdAdK7eCIGDIs2oymuVe2mgSc/e64sfjKr/WxFlVgaNXgiAi+Qrz/oxaLt9yUHOGOxGjaZOAAEzRCuvZrrQZ/LWODzoBgAy7NGRu38qvaDSZvdMYfqQL27myJO/wbOGpLcc9tC04vjy5Y8lM3/9qfY6y3sE/84Y5INewe7QgNw0FGPoscIhWGT5jrZcKQE2lxtxLbQK3/GdgoIl4yYkAk9WWqPZKB7vjU=
